Repository CodenameCrew/CodenameEngine, pull requests merged in 2025-07, with the labels that each got.

#662 Week6 pixel fix
  assets/data/scripts/pixel.hx
  assets/data/scripts/week6-pause.hx
  assets/data/scripts/week7-balledLines.hx
  assets/data/stages/tank.hx
Labels: type:bug

#669 Update FreeplayState.hx
  source/funkin/backend/chart/Chart.hx
  source/funkin/backend/chart/ChartData.hx
  source/funkin/editors/charter/Charter.hx
  source/funkin/editors/charter/CharterMetaDataScreen.hx
  source/funkin/editors/charter/CharterSelection.hx
  source/funkin/editors/charter/SongCreationScreen.hx
  source/funkin/menus/FreeplayState.hx
Labels: status:accepted

#666 FINALLY fixed the issue with GlobalState blowing up when pressing F5.
  assets/data/global.hx
  assets/songs/stress/cutscene.hx
  source/funkin/backend/MusicBeatState.hx
  source/funkin/backend/MusicBeatSubstate.hx
  source/funkin/backend/scripting/GlobalScript.hx
  source/funkin/backend/scripting/ScriptPack.hx
  source/funkin/backend/system/Controls.hx
  source/funkin/game/PlayState.hx
  source/funkin/options/Options.hx
  source/funkin/options/keybinds/KeybindsOptions.hx
Labels: type:bug, type:enhancement, status:reproducible, status:awaiting

#664 a little charter bugfixs and dont show strumlines locks if there no strumline in the chart
  source/funkin/editors/charter/Charter.hx
  source/funkin/editors/charter/CharterStrumlineButton.hx
Labels: type:bug

#518 [ENHANCEMENT] Add Volume Keys to Controls
  source/funkin/options/Options.hx
  source/funkin/options/keybinds/KeybindsOptions.hx
Labels: type:enhancement
